name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install -U platformio
           platformio upgrade
           platformio update

      # Runs a set of commands using the runners shell
      - name: Run PlatformIO
        run: platformio run -d /tmp/epimetheus-main
