name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install platformio
           wget https://github.com/usini/epimetheus/archive/main.zip -O /tmp/main.zip
           unzip /tmp/main.zip -d /tmp

      # Runs a set of commands using the runners shell
      - name: Run PlatformIO
        run: platformio ci --lib="." --lib="/tmp/epimetheus-main"
